---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: Generic template 👤
reponame: template-generic
repourl: https://github.com/radio-aktywne/template-generic
templatename: generic
type: generic
